### ISSUE TITLE
Common.Logging.NLog41 binding to NLog should be changed back to version 4.0.0.0 instead of 4.1.0.0

### ISSUE THREAD

**Issue by DannyVarod** [net-commons/common-logging#102]
NLog 4.1.0 was accidently released as AssemblyVersion 4.1.0.0 instead of 4.0.0.0.
This was amended in version 4.1.1, however, anyone using Common.Logging.NLog41 will not be able to use NLog 4.1.1+.

See: http://nlog-project.org/2015/09/12/nlog-4-1-1-has-been-released.html
and: https://github.com/NLog/NLog/issues/921

Also, I really don't see why each version of NLog should have its own adaptor instead of using a single adaptor e.g. Common.Logging.NLog and letting consumers add bindingRedirect (which the NuGet manager does automatically when you update a NuGet) when they update NLog prior to the adaptor being updated.

**Comment by 304NotModified** [comment]
@DannyVarod Thanks for posting here.

I propose to update the [Common.Logging.NLog41  package ](https://www.nuget.org/packages/Common.Logging.NLog41): 

- Rebuild with 4.1.1 
- Change the dependency to NLog 4.1.1+ 

The goods news, in the future there is no need to create a new Common.Logging.NLog4X. As we're release more often, it saves some effort :)

@ nlog users: sorry for the inconvenience.

**Comment by StasPerekrestov** [comment]
Thanks

**Comment by 304NotModified** [comment]
Bump

**Comment by yyjdelete** [comment]
So, this mean I should use Common.Logging.NLog40 for NLog 4.1.1+ in the meantime ?

**Comment by 304NotModified** [comment]
Yes indeed :)

**Comment by 304NotModified** [comment]
Is this repository even active? This is a easy change? @sbohlen?

**Comment by sbohlen** [comment]
I'm traveling and won't be able to look into this until early next week.

**Comment by 304NotModified** [comment]
OK thanks for the up!

**Comment by DanubeRS** [comment]
@304NotModified This is just an assumption, but given your versioning, this would also make usage of your 4.2.0 release usable with Common.Logging.NLog40?

**Comment by 304NotModified** [comment]
@DanubeRS, no it's just the other way: every NLog 4.x.y release work or will work with Common.logging.Nlog40. (with only 4.1.0 as an exception) . So 4.2.0 will work. 

That's because we don't bump assembly versions and we conform to semver.

**Comment by DanubeRS** [comment]
Sorry, thats what I meant. Tried it shortly after and it works fine.

**Comment by 304NotModified** [comment]
OK :)

So to be clear: the Common.Logging.NLog41 package is not needed anymore (well, only for 4.1.0). But if you now install Common.Logging.NLog41 and then upgrade NLog, you get serious problems  (nuget won't handle the strong name change well).
