### ISSUE TITLE
Common.Logging.WinRT depends on Common.Logging.Core, but core does not provide wpa81 target

### ISSUE THREAD

**Issue by jpikerun** [net-commons/common-logging#103]
The Common.Logging.Core nuspec needs to be updated to include support for wpa81.  I cannot install the Common.Logging.WinRT nuget into a Window Phone 8.1 project because the dependency on Common.Logging.Core fails.

**Comment by sbohlen** [comment]
I'm traveling and won't be able to look into this until early next week.

**Comment by mikegottlieb** [comment]
Any news on this? I still get the same error.

**Comment by sbohlen** [comment]
Sorry about the delay; I'll look into resolving this for you first thing tomorrow morning.  At first glance it sounds like (mostly?) just a package metadata oversight; AFAIK we're not doing anything that would preclude support for the WP8.1 TFM.

-----Original Message-----

**Comment by jpikerun** [comment]
Agreed. I think it is just a nuspec issue.

**Comment by sbohlen** [comment]
Actually, as I look into this, it might be a bit more complicated than just correcting NuSpec metadata.  In Visual Studio (2015, Update 2) I'm precluded from adding a reference of `Common.Logging.Core` into `Common.Logging.WinRT` with a "the portable targets are not the same or compatible" error.

I'd be interested in any input from anyone as to _why_ this is the case.  As far as I can tell, the PCL targets that are declared in `Common.Logging.WinRT` are a subset of the targets declared in `Common.Logging.Core` as follows:

`Common.Logging.Core` targets:
* .NET Framework 4
* Silverlight 5
* Windows 8
* Windows Phone 8.1
* Windows Phone Silverlight 8

`Common.Logging.WinRT` targets:
* .NET Framework 4.5
* Windows 8
* Windows Phone 8.1

The only (apparent) mismatch I can see here would be that `Common.Logging.Core` targets .NET 4 whereas `Common.Logging.WinRT` targets .NET 4.5.  But I always understood .NET 4.5 to be a full proper superset of .NET 4 (i.e., there isn't anything in .NET 4 that's not also in .NET 4.5, meaning it should be possible for a .NET 4.5 assembly to reference a .NET 4 assembly as I'm attempting here).  However the tooling seems to vehemently disagree with my understanding :-/

Obviously at _some point_ I was able to add the reference successfully (else how would the entry be in the .csproj file in the first place?), but now the solution explorer is displaying a "yellow triangle" warning icon on the reference and the tooling refuses to let me re-add the reference if I remove it and attempt to re-add it back.

This suggests that while I _might_ be able to correct the initially-reported issue by tweaking the NuSpec metadata to add a declaration of support for WPA8.1, this may only uncover the next error: a runtime failure when the consuming app attempts to load the `Common.Logging.Core` assembly. 

I'm continuing to try to puzzle this one out, but if anyone has any insight into this that they can offer, I'd certainly appreciate it to speed me along to a resolution...at first glance this has me a bit baffled...

**Comment by sbohlen** [comment]
Circling back on this to share an update....

I've performed further testing and exploration into this and I am now 99% convinced that this is a tooling bug in the add-reference tool in VS 2015.  I'm currently running VS 2015 Update 2 and unfortunately I don't have a system with VS 2015 pre-Update 2 to help determine _exactly_ when this behavior changed.  However I was able to find a system with VS 2013 installed and test this very same cross-PCL-reference scenario -- the result is that this same set of PCL targets referencing between each other in VS 2013 seems entirely acceptable/proper (as one would expect).

I'm seeking to get 100% confirmation that this isn't an _intentional_ change in the rules about what PCLs are permitted to reference each other, but assuming that I can achieve certainty on this point I'd expect to be able to correct the NuSpec metadata appropriately and push an updated package shortly.

Thanks for everyone's patience as we puzzle this one out ...

**Comment by mikegottlieb** [comment]
@sbohlen Thanks for following up on this. I'm building an app using Xamarin for iOS, Android, and Windows Phone 8.1 specifically (yeah I know, but its not my call). It is incredible how little support is available when you add Windows Phone 8.1 into the mix. Half of Xamarin's own libraries barely work. I really appreciate you looking into this.

**Comment by sbohlen** [comment]
FWIW I've now managed to (finally) confirm that https://github.com/net-commons/common-logging/issues/103#issuecomment-218867074 is indeed a bug in VS 2015.  It first appeared in Update 1 and is still present in Update 2 and is related to the introduction of support for .NET Core that was added to the PCL-compatibility-checker that validates attempts to cross-reference assemblies during the add-reference experience.

Now that I know what's going on there, I can return to fix this specific packaging/metadata issue.  I don't have time to see to it today, but its on my TODO list for first thing tomorrow a.m. so look for an updated NuGet package that addresses this issue in < 24 hours.

Thanks for your patience on this, everyone!

**Comment by sbohlen** [comment]
This is fixed in https://github.com/net-commons/common-logging/commit/6ab4a9835f0ccad1cd8c81c410a0323b5e3e71fe and has been pushed to NuGet as 3.3.2-Alpha1 and will be included in the official release of 3.3.2 (and forward).  I'm going to close this issue for now -- if by chance this fails to properly fix the issue, please return here and re-open this issue accordingly.

Thanks again for you patience on this!

**Comment by mikegottlieb** [comment]
Awesome!
