### ISSUE TITLE
Cannot add Common.Logging.Core to PCL with profile 259

### ISSUE THREAD

**Issue by fubar-coder** [net-commons/common-logging#105]
Profile 259 includes .NET 4.5, Win8, WP Silverlight 8.1, ASP.NET Core 5.0, WP 8.1, and (optionally) all the Xamarin stuff.

**Comment by sbohlen** [comment]
I'm traveling and won't be able to look into this until early next week.

**Comment by tofutim** [comment]
any progress on this?

**Comment by gjkhw** [comment]
My team also has this problem.  We are seeing it on Macs and PCs running both the latest released Xamarin Studio, and the newer alpha that is built on nuget 3.5.

My Windows box with Visual Studio 2015 is being serviced by IT at the moment, but I will work on tracking this down, looking for a solution that works on both Windows and Mac, as soon as I get it back, hopefully in the next day.

A coworker had success repacking the nuget by adding a extra targets to the nuspecs for Common.Logging.Portable:
` <file src="..\..\build\portable\Common.Logging.Portable\Release\Common.Logging.Portable.dll" target="lib\portable-net45+win8+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />`

and Common.Logging.Core:
`    <file src="..\..\build\portable\Common.Logging.Core\Release\Common.Logging.Core.dll" target="lib\portable-wpa81+win8+win81+uap10.0" />
    <file src="..\..\build\portable\Common.Logging.Core\Release\Common.Logging.Core.xml" target="lib\portable-wpa81+win8+win81+uap10.0" />
    <file src="..\..\build\portable\Common.Logging.Core\Release\Common.Logging.Core.dll" target="lib\portable-net45+win8+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />
    <file src="..\..\build\portable\Common.Logging.Core\Release\Common.Logging.Core.xml" target="lib\portable-net45+win8+wpa81+MonoAndroid10+xamarinios10+MonoTouch10" />`

I think that we should be able to do better than that.  I will see if I can learn anything in the next few days, once I get my Windows box back.

**Comment by gjkhw** [comment]
Profile 259 is described with a target of portable-wpa81+win8+win81 per https://docs.nuget.org/ndocs/schema/target-frameworks .

The Common.Logging.Core.2010 project's output assembly targets Profile 328.  The same binary DLL is being packaged for netstandard1.0, portable-win+net40+sl40+wp7+wpa81, and net40.  None of those profiles are compatible with Profile 259.

However, Profile 328 is compatible with Profile 259 per http://nugettoolsdev.azurewebsites.net/3.5.0-beta2-1484/get-nearest-framework?project=portable-wpa81%2Bwin8%2Bwin81&package=portable-net40%2Bsl5%2Bwin8%2Bwpa81%2Bwp8

The Common.Logging.Portable.2010 project's output assembly targets profile 136.  The same binary DLL is being packaged for portable-win+net40+sl40+wp7, net40, and net35.  None of those profiles are supposed to be compatible with Profile 259 per http://nugettoolsdev.azurewebsites.net/3.5.0-beta2-1484/get-nearest-framework?project=portable-wpa81%2Bwin8%2Bwin81&package=portable-win%2Bnet40%2Bsl40%2Bwp7%0D%0Anet40%0D%0Anet35%0D%0A but the DLL is working, at least in the projects that I'm running it in.

I see a few paths forward - either add a target for portable-wpa81+win8+win81 to at least Common.Logging.Core and Common.Logging.Portable, and just copy the existing Profile 328 and 136 DLLs to it.  

Another would be to add new projects that have Profile 259 outputs for Common.Logging.Core and Common.Logging.Portable.  

I don't know if there are any cons to the former - it seems simpler.  The latter might give a stronger compile-time guarantee that you aren't using any symbols that aren't available to Profile259, I guess.

**Comment by sbohlen** [comment]
We'll look to resolve this shortly and re-issue another 3.4-pre-release package for testing.

**Comment by sbohlen** [comment]
Closing this as fixed in `Common.Logging` `3.4-RC1`
