### ISSUE TITLE
Question: Common.Logging.Portable application in a PCL code

### ISSUE THREAD

**Issue by blsmithers** [net-commons/common-logging#106]
I'm looking at the response for the linked question: https://github.com/net-commons/common-logging/issues/99

I'm imagining the scenario described which was very helpful:

YourPCLProject
  --ref--> Common.Logging.Portable.dll

SomeNonPCLProject
  --ref--> YourPCLProject
  --ref--> Common.Logging.Portable.dll
  --ref--> Common.Logging.Log4Net1211.dll
  --ref--> Log4Net.dll

However the problem I'm running up against is Common.Logging.Log4Net1213 depends on the Common.Logging.dll not the Common.Loggin.Portable.dll so I'm having trouble figuring out how to properly hook log4net into the portable version of LogManager

**Comment by sbohlen** [comment]
I'm traveling and won't be able to look into this until early next week.

**Comment by sbohlen** [comment]
Sorry for the delay in getting back to you on this.  I think that the failure was in my initial answer to the other question.

The way the answer _should_ have read was as follows (changes in **bold**):

YourPCLProject
--ref--> **Common.Logging.Core.dll**

SomeNonPCLProject
--ref--> YourPCLProject
--ref--> **Common.Logging.dll**
--ref--> Common.Logging.Log4Net1211.dll
--ref--> Log4Net.dll

I apologize for my error.  Common.Logging.Portable.dll wasn't intended for this use case (as I'd erroneously suggested in my prior answer).  In your case, your PCL lib should reference only Common.Logging.Core (which _is_ properly shared between Common.Logging.Portable and Common.Logging).

Does that help clarify the intent --?

**Comment by blsmithers** [comment]
Yes that makes perfect sense, thanks for getting back to me!
