### ISSUE TITLE
Keyfile is missing

### ISSUE THREAD

**Issue by kerryjiang** [net-commons/common-logging#11]
When I ran build-release.cmd, it gave me the key file missing error:
project.sign='true' but keyfile D:\kerry\workshop\common-logging/Common.Net.snk is missing

Can I generate the keyfile by myself?

**Comment by gigi81** [comment]
@sbohlen I understand what you were saying 5 years ago, but what if there is a problem with the nuget package and you guys don't fix it?
There hasn't been a release of this library for over 2 and a half years now.
I honestly don't see the security risk in publishing the key. Even the log4net guys decided to publish it in the end for the same reason, see https://github.com/apache/logging-log4net/blob/master/log4net.snk.readme
