### ISSUE TITLE
memory leak with log4net 

### ISSUE THREAD

**Issue by yoshia0305** [net-commons/common-logging#116]
Hello,

I often encounter a memory leak issue when using common log with log4net for my web project. Once any of my pages is request, memory usage is increased higher and higher. Not always, but often. Could anybody give me a hint? Thanks.

My environment could be found with attachment.

[Web.config.TXT](https://github.com/net-commons/common-logging/files/95503/Web.config.TXT)
[log4net.confi.TXT](https://github.com/net-commons/common-logging/files/95502/log4net.confi.TXT)

**Comment by yoshia0305** [comment]
It is a bug of log4net.
https://issues.apache.org/jira/browse/LOG4NET-82
https://issues.apache.org/jira/browse/LOG4NET-367

**Comment by Alex--Jin** [comment]
is there any solution? please advise.
Thank you.

**Comment by yoshia0305** [comment]
In my case (a web project), it is caused by invalid physical log file setting.
before:
`
<file value="C:/my_folder/my.log" />
<datePattern value=".yyyyMMdd" />
`
after:
`
<file value="C:/my_folder/" />
<datePattern value="my.lo\g.yyyyMMdd" />
`

BTW, to identify the issue, it is suggested to enable log4net internal log.
