### ISSUE TITLE
Common.Logging.NLog20 with .Net 2.0

### ISSUE THREAD

**Issue by techgeek03** [net-commons/common-logging#122]
Hello,

Common.Logging.NLog20 Nuget package does not target .Net framework 2.0 where NLog 2.1.0 is the latest version form NLog that supports .Net 2.0. 
You need to include the correct support. 
Thanks!

**Comment by sbohlen** [comment]
Thanks for catching this; its definitely a NuGet packaging oversight on our part.  We'll add .NET 2.0 to the packaging metadata and include it in the next push/update (its likely that we'll push a formal 3.4 release to NuGet once the work on https://github.com/net-commons/common-logging/issues/121 is completed).

**Comment by techgeek03** [comment]
Thank you very mach! It will certainly be helpful for all those legacy project that we still need to maintain.

**Comment by sbohlen** [comment]
This is fixed in https://github.com/net-commons/common-logging/commit/a843f874d94e8af1fc24079dd8b3c6aaa149971d and will shortly be pushed to NuGet as 3.4-alpha1; assuming nobody reports any issue w/ it, it will become official once 3.4 goes GA (hopefully by mid-JULY).
