### ISSUE TITLE
Extend ThreadVariablesContext To Support Stacks

### ISSUE THREAD

**Issue by Moily** [net-commons/common-logging#128]
Given that nested contexts are supported in a range of different logging components would it be possible to extend the `ThreadVariablesContext` member on `ILog` to include support for the underlying stack operations so that NDC-style contexts can be supported through Common.Logging? 

These new members would then map to equivalent members on `ThreadContext.Stacks["NDC"]` for log4net, `NestedDiagnosticsContext` for NLog, `LogContext` for Serilog, and so on, to provide common NDC functionality across logger components.

**Comment by sbohlen** [comment]
Interesting suggestion; do you have any thoughts about what this support might look like?

**Comment by Moily** [comment]
Initital thoughts were an additional or derived interface with the stack operations on that are utilised by NDCs.  The type used for `ThreadVariablesContext` would then implement this and map those operations onto the corresponding members of the actual loggers.

I'll fork and try it out first and issue a PR if all well and good, if that's ok?

**Comment by sbohlen** [comment]
Yes, that would be great; let me know if you run into any issues with which we can assist!

**Comment by Moily** [comment]
Pull Request created: #129

**Comment by Moily** [comment]
Additional Pull Request created: #131

**Comment by sbohlen** [comment]
PR https://github.com/net-commons/common-logging/pull/131 merged; thanks for the contribution!
