### ISSUE TITLE
Support for ASP.Net Core

### ISSUE THREAD

**Issue by isaac2004** [net-commons/common-logging#139]
Is there something on the roadmap to support ASP.NET CORE?

**Comment by tynorton** [comment]
👍  Would also like to know this.

**Comment by bencameron00** [comment]
I am waiting for this for a project that I am currently working on also. Common Logging is great and I am hoping that I can keep using it with .net core. Any roadmap timings would be great.

**Comment by sbohlen** [comment]
The thinking right now is that the roadmap would be for us to resolve the remaining PCL packaging/targeting issues with the current 3.4-beta and then to attempt to pivot to 4.0, which would switch to the ".NET Standard" packaging targets with the intent of having a .NET Core support story to it.

**Comment by sbohlen** [comment]
Closed as superseded by #148.

**Comment by isaac2004** [comment]
Just checked that out, exactly what I was hoping the approach was going to be. As a developer I want to work on fresh bits, and something like this provides additional ammo to sell to stakeholders. Thanks again! On a side note, took a long time to get a roadmap :)

**Comment by sbohlen** [comment]
@isaac2004 yes, and trust me nobody is less happy about the pace than myself.  Things will pick up shortly once `3.4-GA` is released (as soon as I can package the bits) and we can move on to focus on `4.0`
