### ISSUE TITLE
relax the log4net dependency version

### ISSUE THREAD

**Issue by jjanuszkiewicz** [net-commons/common-logging#140]
I can see that the latest log4net integration package (Common.Logging.Log4Net1215) depends strictly on log4net [2.0.5].

Would it be possible to relax it to something like [2.0.5,3.0), which will allow to update to a compatible (due to semantic versioning) log4net version without the need to update Common.Logging.Log4NetNNN every time? Also future versions of this package could have similar dependency as well. On top of that, I can see that there is no package for log4net 2.0.4 yet, I'd like to create one if that's not a problem - it could already use the less strict dependency.

The reason behind this is that having a strict dependency like this forces a wave of updates across the whole codebase which happens to share any project which gets updated to a new log4net version, which in case of my job is hundreds of projects in dozens of solutions, in dozens of repositories, which is basically an impossible (=too expensive) task.

I will create a pull request if I get an approval for such a change.

**Comment by sbohlen** [comment]
Unfortunately, while you're right that making such a change would solve that _specific_ problem, it also introduces others.  In fact, `Common.Logging` _used_ to work that way re: versioning and dependencies, but we explicitly abandoned the strategy some time ago as laid out in [the wiki here](https://github.com/net-commons/common-logging/wiki/Common.Logging-Packaging-and-Versions).

Ironically, it was actually `Log4Net` failing to respect SemVer that introduced cascading breaking changes that flowed to adopters of `Common.Logging.Log4Net` that was the genesis of our having to re-think the way that we handled such dependencies.  It may well be that `Log4Net` _now_ respects SemVer, but for quite some time it (and other logging packages) didn't properly do so.  In this context, we'd no choice but to switch to a versioning/dependency scheme for `Common.Logging` adapters that shielded adopters from inadvertent breaking changes introduced by the loggers themselves.  This goal was seemingly best achieved by locking in the dependency for each adapter to only a _single specific version_ of a logger, as is the case now.

The current scheme enables adopters to mix-and-match versions of `Common.Logging` with adapters for whatever version of the logger you choose.  Its certainly true that this flexibility comes with a certain maintenance overhead in scenarios such as yours, but we'd determined that this was a better solution than permitting NuGet to introduce a breaking change by pulling down a logger against which the `Common.Logging` adapter had never actually been tested.  Indeed, when `Log4Net` introduced their non-SemVer-respecting breaking change, we received a lot of "`Common.Logging.Log4Net` is broken" reports that were (of course) not the 'fault' of `Common.Logging` at all, but appeared that way b/c the origin of the errors was inside our (newly-incompatible) adapter for `Log4Net`.

That said, clearly the present approach we've adopted isn't perfect either (for the reasons you identify).  We're certainly more than willing to entertain suggestions re: how we might better be able to address both of these needs that seem to be in diametric opposition to each other -- can you perhaps suggest another approach that would be able to better satisfy both sides of this problem --?

**Comment by sbohlen** [comment]
Closing this issue as WONTFIX.
