### ISSUE TITLE
Add Xamarin support to NLog packages

### ISSUE THREAD

**Issue by MKuckert** [net-commons/common-logging#141]
Currently the NLog packages can't be used in a Xamarin.iOS project. NuGet throws the following error when trying to install the `Common.Logging.NLog41` package, even when using `Beta2`:
`Could not install package 'Common.Logging.NLog41 3.4.0-Beta2'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`
For me it looks like the NLog package is a .Net library only. That may be the cause.

**Comment by sbohlen** [comment]
Confirming that NLog 4.1 only support full .NET Framework (see https://www.nuget.org/packages/NLog/4.1.0).  Closing this issue accordingly.

**Comment by MKuckert** [comment]
I'm not sure what you're referring to but according to http://nlog-project.org/ NLog supports the following platforms:
- .NET Framework 3.5, 4, 4.5 & 4.6
- Xamarin Android
- Xamarin iOs
- Windows Phone 8
- Silverlight 4 and 5
- Mono 4
- ASP.NET 4 (NLog.Web package)
- ASP.NET Core (NLog.Web.AspNetCore package)
- .NET Core (NLog.Extensions.Logging package)

I've successfully used Common Logging in conjunction with NLog (not directly using the NuGet Packages but building the projects on my own). Can I provide any help?

**Comment by sbohlen** [comment]
[Re-opening this issue]

Actually, yes.  If you're willing it would be helpful if you could assist in confirming/validating several of our conclusions.

1. For clarity, our conclusion as to `NLog` support for other TFMs than the full .NET Framework is specifically about `NLog` **4.1**.  We'd focused on that version of `NLog` b/c the original post referenced a repro that involved that specific version of `NLog`.  When we installed the `NLog` 4.1 NuGet package into a new/empty folder (e.g., "`nuget.exe install nlog -version 4.1`") the resulting /lib/ folder structure contains binaries for the full .NET Framework and SL4 + 5, but definitely _not_ Mono.  **Could you attempt to add `NLog` 4.1 to a Mono project (not involving` Common.Logging` at all) and advise whether this is supported?**  We suspect _not_, hence the closure of this issue, but we may well be wrong too :)

1. I'm not certain, but I believe that list of supported TFMs for NLog you are referencing is in re: the latest version of NLog (i.e., 4.4.11, https://www.nuget.org/packages/NLog/4.4.11 or even perhaps 5.0 beta).  **Could you attempt to add `Common.Logging.NLog4411` (https://www.nuget.org/packages/Common.Logging.NLog4411/3.4.0) to a Mono project and advise your results?**  With the (recent) release of `Common.Logging` 3.4 to GA, `Common.Logging.NLog4411` is _expected_ to be a combination of dependencies that _should_ properly support Mono.

Thanks in advance for you willingness to assist on this!

**Comment by MKuckert** [comment]
You are totally right: `NLog` 4.1 does not support Xamarin.iOS but 4.4.11 does. I tried to install the according NuGet Packages into an iOS project.

Installing NLog 4.1 returns the error: `Could not install package 'NLog 4.1.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Installing NLog 4.4.11 is successful. But installing `Common.Logging.NLog4411 (version 3.4.0)` returns the error: `Could not install package 'Common.Logging.NLog4411 3.4.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`.

`Common.Logging.NLog4411` contains only a dll for `net40`, non for `Xamarin.iOS10`.

**Comment by sbohlen** [comment]
Thanks for the input and the error report.

I'll take a look @ the `Common.Logging.NLog4411` package and see what went wrong.  Clearly there's a packaging problem on our end; if NLog 4411 supports those broader list of targets then we should be providing a matching binary in `Common.Logging.NLog4411` for each as well.  I'll dig into it shortly and advise.

When (we think) we've got it fixed, we'll release a set of 3.4.1-Alpha1 packages.  We'd appreciate it if you'd be willing to test this again once that's pushed to NuGet, as I've not got Xamarin installed on any of my systems running Visual Studio and I'd rather not spend the ~40GB in disk space for 20 versions of Java just to test the NuGet installer results if I can avoid it :)

Thanks again!

**Comment by MKuckert** [comment]
Sure. Just let me know and I'll test your NuGet Beta packages.

**Comment by sbohlen** [comment]
@MKuckert I'm trying to determine specifically what PCL profile(s) are needed for Xamarin support.  From [this section](https://developer.xamarin.com/guides/cross-platform/application_fundamentals/pcl/introduction_to_portable_class_libraries/#What_is_a_Portable_Class_Library) in the Xamarin docs comes the following excerpt (emphasis mine):

>The Xamarin column reflects the fact that **Xamarin.iOS and Xamarin.Android supports all the profiles shipped with Visual Studio 2013 and above**, and the availability of features in any libraries you create will only be limited by the other platforms you choose to support (such as Windows Phone or Windows Store).
>
>This includes profiles that are combinations of:
>
>* .NET 4 or .NET 4.5
>* Silverlight 5
>* Windows Phone 8
>* Windows Store Apps

If that's correct, then it would seem on its surface that the binary in the `Common.Logging.NLog4411` package (e.g. in the `net40` folder) should be compatible with Xamarin (?)  If this is true, then it would seem that just a change to the NuGet package to place the _same_ binary into a `Xamarin.iOS` folder would be all that's required to properly support Xamarin.

Would you be willing to perform the following test and advise results?

1. Grab the binary from the `Common.Logging.NLof1411` package (`net40` folder)
1. Reference it (by hand, not via NuGet) into your Xamarin project.
1. Build/run and report results

If `Xamarin.iOS` is really a superset of `net40` as this reference doc excerpt implies, its not at all clear to me why NuGet wouldn't accept the `net40` binary package into a `Xamarin.iOS`-targeted project.  But if this section is correct, then a simple adjustment to the structure of the NuGet package would seemingly be all that's needed here.

Thanks in advance for you (continued) help~!

**Comment by MKuckert** [comment]
I just tested the referencing as suggested and you're right: I can successfully reference and leverage the Common.Logging `net40`-dlls from within my iOS project. The NLog adapter can be used with this setup 👍 But I have to target NLogs `Xamarin.iOS` to work – the `net40` dll throws any `type not found` exception otherwise. But that's no problem in the case of installing via NuGet.

So yes, you should be able to use the `net40` dll when bundling the NuGet package to target `Xamarin.iOS` projects as far as I understand.

**Comment by sbohlen** [comment]
Thanks for the validation.  We've pushed `3.4.1-RC1` packages to NuGet.

As a _final_ test/verification before we release this change formally, would you be willing to attempt to add [this pre-release version of the `Common.Logging.NLog4411` package](https://www.nuget.org/packages/Common.Logging.NLog4411/3.4.1-RC1) to your Xamarin project and report results?

Assuming you report OK, we'll move to `3.4.1-GA` and publish that shortly (along with a similarly-configured package for NLog 4.4.12, which we noticed has just been released in the last week).

Thanks again for your continued assistance on this; its much appreciated~!

**Comment by MKuckert** [comment]
Looks very good! I can successfully install the NuGet package `3.4.1-RC1` in an iOS project. The NLog dependencies are successfully resolved and installed. 👍

**Comment by sbohlen** [comment]
Excellent; we'll release this to NuGet (along with parallel support for NLog 4.4.12) later today.

Thanks again~!

**Comment by sbohlen** [comment]
Resolved in https://github.com/net-commons/common-logging/tree/3.4.1.GA
