### ISSUE TITLE
Is there an example of using Common Logging with .Net Core 2.0?

### ISSUE THREAD

**Issue by spankr** [net-commons/common-logging#153]
I spent a bit of time digging around, trying to find an example of a NETCore 2.0 app that used Common Logging 3.4.1 (with NLog) and couldn't find one.
In the end, I figured it out on my own through trial & error.
(I'm eagerly waiting for Common Logging 4.x!)

Is there an official example available (that I couldn't find)?

If not, here is what I had to do:

```c#
    class Program
    {
        // Must be done (just once!) before any loggers are instantiated
        private static void SetupLogging()
        {
            var props = new Common.Logging.Configuration.NameValueCollection
            {
                { "configType", "FILE" },
                { "configFile", "./nlog.config" }
            };
            LogManager.Adapter = new Common.Logging.NLog.NLogLoggerFactoryAdapter(props);
        }

        static void Main(string[] args)
        {
            SetupLogging();

            var logger = LogManager.GetLogger<Program>();

            logger.Info("Hello World.");
            Console.ReadKey();
        }
  }
```

The issue I had was that in netcore20, finding configuration files is a lot different. _(nlog.config file has to be available in the executing folder in this snippet)_

**Comment by Troncek** [comment]
Here's another example using appsettings.json instead of setting it up programmatically .

`{
  "LogConfiguration": {
    "factoryAdapter": {
      "type": "Common.Logging.NLog.NLogLoggerFactoryAdapter, Common.Logging.NLog4412",
      "arguments": {
        "configType": "FILE",
        "configFile": "~/nlog.config"
      }
    }
  }
}`

`using Common.Logging;
using Common.Logging.Configuration;
using Microsoft.Extensions.Configuration;

      IConfiguration config = new ConfigurationBuilder()
        .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
        .Build();

      LogConfiguration logConfiguration = new LogConfiguration();
      config.GetSection("LogConfiguration").Bind(logConfiguration);
      LogManager.Configure(logConfiguration);

..

    private static readonly ILog log = LogManager.GetLogger(typeof(SomeClass));
`

**Comment by spankr** [comment]
Team was asking this question and a google search came back with this page. I like the response provided by @Troncek
