### ISSUE TITLE
GetCurrentClassLogger possible NRE

### ISSUE THREAD

**Issue by chriseldredge** [net-commons/common-logging#22]
[LogManager.GetCurrentClassLogger](https://github.com/net-commons/common-logging/blob/master/src/Common.Logging/Logging/LogManager.cs#L200) uses the DeclaringType from the method info as the current class, but in .net 4.0 and later include [DynamicMethod.DeclaringType](http://msdn.microsoft.com/en-us/library/system.reflection.emit.dynamicmethod.declaringtype.aspx) which is <b>always null</b>.

This causes GetCurrentClassLogger to throw NullReferenceException when invoked from a dynamic method.

I've seen this problem in conjunction with Spring Framework with a proxied type, as in this example stack trace:

    Object reference not set to an instance of an object.
    at Common.Logging.Factory.AbstractCachingLoggerFactoryAdapter.GetLogger(Type type)
    at Common.Logging.LogManager.GetCurrentClassLogger()
    at _dynamic_MyExampleType..ctor(Object[] )
    at Spring.Util.ObjectUtils.InstantiateType(ConstructorInfo constructor, Object[] arguments) in c:\_prj\spring-net\trunk\src\Spring\Spring.Core\Util\ObjectUtils.cs:line 252

Since no declaring type will be available, perhaps throwing a more specific exception instead of NRE is the best fix. Code that worked on .net 3.5 stops working on .net 4.0 because of this bug.

**Comment by sbohlen** [comment]
We've taken the approach some time ago of adding the [Obsolete] attrib to this code path so I'm going to close this issue for the time being.  We can re-open it in the future if someone devises a PR that addresses it any more meaningful manner (though as we've discussed I don't think there's any way to prevent this NRE in any of the use-cases identified in this thread as being potential causes of this issue).
