### ISSUE TITLE
Inefficiency code in 'ErrorFormat' (and other XXXFormat)

### ISSUE THREAD

**Issue by imkevinyang** [net-commons/common-logging#32]
public virtual void ErrorFormat(string format, params object[] args)
    {
        if (this.IsErrorEnabled)
        {
            this.Write(LogLevel.Error, new StringFormatFormattedMessage(null, format, args), null);
        }
    }

every time this XXXFormat is called, a new StringFormatFormattedMessage instance is constructed, which do nothing but call string.Format. 
Why not call string.Format directly since this is called only once. the CachedMessage had not even been used.

    public override string ToString()
    {
        if ((this.cachedMessage == null) && (this.Message != null))
        {
            this.cachedMessage = string.Format(this.FormatProvider, this.Message, this.Args);
        }
        return this.cachedMessage;
    }

**Comment by 304NotModified** [comment]
I think this should be closed. (inactivity)

**Comment by sbohlen** [comment]
Agreed.  We can re-open this later if needed.
