### ISSUE TITLE
ELMAH integration

### ISSUE THREAD

**Issue by cmshawns** [net-commons/common-logging#39]
I have taken over ownership of Common.Logging.Elmah

https://github.com/shawn-bellevuecollege/common-logging/tree/master/src/Common.Logging.Elmah

and will like to add it to the loggers & adapters included with Common.Logging. When ready, a pull request will be attached to this issue.

ref: http://www.dotblogs.com.tw/wadehuang36/archive/2011/10/06/Common-Logging-Elmah.aspx

**Comment by sbohlen** [comment]
@cmshawns:

Are you still running Common.Logging.Elmah?  If so, I'd like to re-open this discussion to see how we can accommodate you...(and, yes, I know its been a while on this thread :-/)

**Comment by cmshawns** [comment]
I am not, sorry. Work wasn't interested in following up and I've moved on to other employment. I'd be happy to contribute to any discussion, though. And am perfectly willing to transfer ownership of the repo, if there's somebody who wants to take it over.

**Comment by sbohlen** [comment]
Thanks for getting back to us.

We'd be happy to fold it into the main Common.Logging project if you'd be willing to transfer the repo to either myself or the net-commons organization so that we can adequately maintain it directly...

-----Original Message-----

**Comment by cmshawns** [comment]
Transfer request submitted.

**Comment by sbohlen** [comment]
Got it -- thanks!
