### ISSUE TITLE
Add Change Log for 2.2.0

### ISSUE THREAD

**Issue by karldodd** [net-commons/common-logging#46]
Common.Logging 2.2.0 has been released on nuget.org with a new assembly Common.Logging.Core. But the document has not been updated yet. Just a few sentences on what's been changed/added will help a lot. Thanks.

**Comment by DannyVarod** [comment]
You should edit the title from "documents" to "change log" to make the request more clear.

**Comment by sbohlen** [comment]
ChangeLog.txt now updated through v3.1.0 in https://github.com/net-commons/common-logging/commit/99b77004982dbe3aaa656080550e1191995c12a4; thanks for the reminder!
