### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by azzlack** [net-commons/common-logging#57]
Please add support for Xamarin 3. It shares the same capabilities as win8 and wpa81, so should be as easy as adding a new folder in the nuget lib folder called `portable-net45+netcore45+wpa81+MonoAndroid1+MonoTouch1` (taken from http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY/preview) and dropping the dll in there.

**Comment by 304NotModified** [comment]
FYI you can run Xamarin Android / iOS  on Appveyor.  We ate doing that right now for NLog 4.3 alpha. 

http://www.appveyor.com/docs/lang/xamarin

License:
https://resources.xamarin.com/open-source-contributor.html


Dunno how to run unit tests, yet.

**Comment by sbohlen** [comment]
Thanks, that's good to know.  I'll look into that -- we're already building on Appveyor so hopefully this will make it easier/straightforward to properly add this.

-Steve B.

-----Original Message-----

**Comment by SchalkVersteeg** [comment]
Hi Steve,

I am struggling to add Common.Logging.Core and Common.Logging.Portable to my Xamarin.Android project, Common.Logging.Core 3.3.1, had a look at #78 and think this is the same issue, thus I had a look at the directory structure of Xamarin.Forms, which do install on MonoAndroid and Xamarin.IOS.

Here is a screen shot of the Xamarin.Forms pcl nuget directory structure, which is working.
*(Note the MonoAndroid10, MonoTouch10 and Xamarin.iOS10 additions)*
![image](https://cloud.githubusercontent.com/assets/7126541/12295664/3f3ba59c-ba0b-11e5-9414-7da0a862d1a2.png)

*Also the following Directory:*
portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10


Hope this help.

**Comment by brantburnett** [comment]
Just wanted to let you guys know that I recently got Common.Logging working on the latest version of Xamarin using the new NetStandard 1.3 binaries in 3.4.0-alpha2.  Just had to manually configure by setting Common.Logging.LogManager.Adapter to the logging adapter during startup.

Here is the blog about using NetStandard PCLs in Xamarin: https://blog.xamarin.com/net-standard-library-support-for-xamarin/

Brant

**Comment by sbohlen** [comment]
Thanks for letting us know -- based on this I will close this issue.  If it turns out that (for some reason) the NetStandard PCLs are insufficient for Xamarin support we can re-open this issue as needed at that time.
