### ISSUE TITLE
Reconsider Architecture/Approach to PCL Support

### ISSUE THREAD

**Issue by sbohlen** [net-commons/common-logging#71]
Creating this issue to centralize actions/discussions related to it.  See https://github.com/net-commons/common-logging/issues/67#issuecomment-62976921 for comprehensive coverage of the background, history, challenges surrounding this.

If anyone has any input/suggestions/etc. on this points raised in https://github.com/net-commons/common-logging/issues/67#issuecomment-62976921 please offer them here -- all ideas are welcome (as always!)

**Comment by sbohlen** [comment]
Just circling back on this; with the release of 3.0.0.GA https://github.com/net-commons/common-logging/tree/3.0.0.GA this strategy is now officially in the wild for formal consumption now.

**Comment by Luceres** [comment]
Hi Steve,
 I just tried to add Common.Logging.Portable to my Xamarin PCL Project, but this didn't work. Before I could add the old Common.Logging.Core. What am I missing?
![error](https://cloud.githubusercontent.com/assets/8191930/5760585/12aab3ae-9cd6-11e4-94fe-a05731e7beb3.jpg)

**Comment by sbohlen** [comment]
The issue you're posting to is CLOSED so we have opened a new issue https://github.com/net-commons/common-logging/issues/78 on your behalf for further investigation into this.  All follow up will occur on that new issue number from this point.
