### ISSUE TITLE
Add Support for NLog 3.2

### ISSUE THREAD

**Issue by sbohlen** [net-commons/common-logging#75]
Per https://www.nuget.org/packages/NLog/ NLog 3.2 was released on 1/2/2015.  We should add formal support for this new version ASAP.

**Comment by lorenh** [comment]
Just curious, will an official NuGet package for Commons.Logging.NLog32 that directly supports NLog 3.2 be created anytime soon?

**Comment by sbohlen** [comment]
Its likely that I'll be able to deal with this over the coming weekend (March 21/22)

**Comment by sbohlen** [comment]
Resolved in commit https://github.com/net-commons/common-logging/commit/54bf1088da331fcd3fb677c7cfc3a561d52b356a.  Will push Common.Logging 3.1.0 to NuGet shortly.

**Comment by lorenh** [comment]
Has the push to NuGet happened yet? Not seeing it.

**Comment by sbohlen** [comment]
Unfortunately, not yet, no.  Unexpected last-minute business travel has
delayed me on this a bit; I'm hoping to get it out tomorrow (3/26).

**Comment by lorenh** [comment]
No problem. Thanks so much for making the change.  Now that I know it won't appear until tomorrow at the earliest I can stop checking.

**Comment by sbohlen** [comment]
This is now complete as of https://github.com/net-commons/common-logging/releases/tag/3.1.0.GA.  My script it pushing the packages to NuGet right now so they should appear there shortly (within 5-10 mins).
