### ISSUE TITLE
Update changelog.txt with v3 release notes

### ISSUE THREAD

**Issue by shatl** [net-commons/common-logging#77]
Please update changelog.txt with release notes.

**Comment by warrenrumak** [comment]
+1, information about 2.3.0 would be useful as well

**Comment by sbohlen** [comment]
Agreed; ChangeLog.txt updated with missing info from 2.2.0 - current (3.1.0) in https://github.com/net-commons/common-logging/commit/99b77004982dbe3aaa656080550e1191995c12a4.  Thanks for the reminder!
