### ISSUE TITLE
Unable to add Common.Logging.Core 3.0 to Xamarin.IOS project

### ISSUE THREAD

**Issue by sbohlen** [net-commons/common-logging#78]
Opening this new issue arising from a comment on another issue that had been closed prior (https://github.com/net-commons/common-logging/issues/71#issuecomment-70105495).

**Comment by sbohlen** [comment]
TBH, I don't know as I don't have (immediate) access to XAMARIN tools to test this myself :(

The updated `Common.Logging.Core` contains the same PCL-supported target list as the prior release, which you can see here https://github.com/net-commons/common-logging/blob/master/src/Common.Logging.Core/Common.Logging.Core.nuspec#L16-L18 as being...
```xml
target="lib\portable-win+net40+sl40+wp7"
```
Since that's not changed, I'm guessing its something else, either on your end or within Common.Logging itself (or its packaging).  Could you please do the following for us:

1. Using NuGet, attempt to reference the prior version of `Common.Logging.Core` into your solution to (re)validate that this still works, helping to reduce the chances that its an issue on your side
2. unzip the NEW (3.0) `Common.Logging.Core` NuGet package to extract the proper binary from the `lib\portable-win+net40+sl40+wp7` folder and attempt to reference it into your project _without_ using NuGet per se.  This will help us identity whether this is an issue with the packaging or the binary itself.

Thanks,

-Steve B.

**Comment by sbohlen** [comment]
FWIW, I just re-read your initial comment and realize that you're also trying to reference `Common.Logging.Portable`.  This should _also_ be supported as its got the same PCL-target-list in its package as does `Common.Logging.Core` (see https://github.com/net-commons/common-logging/blob/master/src/Common.Logging.Portable/Common.Logging.Portable.nuspec#L20-L22) .

However, I'll amend those two testing requests to be "please do the testing steps with _both_ `Common.Logging.Portable` and `Common.Logging.Core`"in order to properly help us puzzle out the problem for you.

**Comment by Luceres** [comment]
Hi Steve,
 bingo - without NuGet it works. Whats wrong here?

![image](https://cloud.githubusercontent.com/assets/8191930/5797952/720a3178-9fc2-11e4-8c38-45791254e54f.png)

Kind regards,

Markus

**Comment by sbohlen** [comment]
OK, thanks for sticking with us on this; thanks to your experimentation I think I've discovered the reason for the behavior you're seeing although I still need to investigate a bit further to track down the root _cause_.

Its definitely a packaging error; as your tests have shown the binaries themselves are just fine.

In the `Common.Logging.Core` version 2.2.1 package, this is the name of the folder in the .nupkg file (under /lib/) that contains the portable binary:

```
portable-win%2Bnet40%2Bsl40%2Bwp7
``` 

However, for `Common.Logging.Core` and `Common.Logging.Portable` version 3.0.0, the name of that same folder instead appears as: 

```
portable-win+net40+sl40+wp7
```
Note that in the one that _works_ (2.2.1) the folder name has the "+" character encoded whereas in the two packages that don't work (3.0.0) the "+" is literal (unencoded).

I'm not (yet) quite sure why/how this didn't happen for the 3.0.0 packaging step, but I'm pretty certain its the cause of the NuGet client's inability to add the 3.0.0 packages to a portable project.  I suspect that the client is parsing the package to discover the folders under /lib/ in the package and isn't finding a match for the project to which you're trying to add it.

I'll do some digging and attempt to puzzle out the cause; as soon as I do we'll have to release an updated 3.0.1 set of packages across the board to address it ASAP.

Standby -- I'll circle back here once that's properly done and then you should be able to prune out your manually-referenced DLLs and replace them with the upcoming 3.0.1 packages we'll release as soon as we solve this.

**Comment by Luceres** [comment]
Hi Steve,
 thank you for your support - thats great!

**Comment by sbohlen** [comment]
Sorry to ask you to validate this again, but can you just confirm for me one last time that you can in fact successfully add the  `Common.Logging.Core` 2.3.1 package to your solution using NuGet?

After further research, I'm less than 100% certain that the (un)encoded "+" is the cause of the error you're seeing with `Common.Logging.Core` and `.Portable` 3.0.0.  But since its your report that the Common.Logging.Core 2.3.1 package _can_ be added via NuGet that is pointing me back to that as the cause, I'd like you to (re)confirm this for me before I head down a rabbit-hole in the wrong direction :)

Thanks for all your assistance here,

-Steve B.

**Comment by Luceres** [comment]
Hi Steve,
 does this help? That´s the dir layout of the solution with the (working) `Common.Logging.Core`

2.2.0 btw

![image](https://cloud.githubusercontent.com/assets/8191930/5822524/29d986e2-a0d5-11e4-83b3-7ad42e54cfa8.png)

**Comment by sbohlen** [comment]
Yes, perfect -- thanks!

**Comment by sbohlen** [comment]
Circling back here, after additional investigation we're unable to determine a reason for the difference in results you're seeing in re: adding 2.2.0 vs. 3.0.0 as both list an _identical_ set of PCL targets in their `nuspec` manifests.

We've posted the issue on the NuGet discussion forum on CodePlex at  https://nuget.codeplex.com/discussions/578408 and hope to hear from the NuGet team on this shortly.

**Comment by sbohlen** [comment]
Were you eventually able to make this work --?  As you can see from the (lack of) activity on the issue I posted to the NuGet codeplex site (https://nuget.codeplex.com/discussions/578408) it seems that nobody there was able (willing? interested?) to try to provide any insight.

As we're unable to identify a cause for the behavior you're seeing and the NuGet team seems inable to assist, I'm leaning towards closing this issue at this time.

Can you advise --?

**Comment by Luceres** [comment]
Hi Steve,

 

on my side this ist he same state as it was. I will try to solve this for myself, close the issue.

 

Thank you for your efforts.

 

Von: Steve Bohlen [mailto:notifications@github.com] 
Gesendet: Montag, 30. März 2015 11:30
An: net-commons/common-logging
Cc: Markus
Betreff: Re: [common-logging] Unable to add Common.Logging.Core 3.0 to Xamarin.IOS project (#78)

 

Were you eventually able to make this work --? As you can see from the (lack of) activity on the issue I posted to the NuGet codeplex site (https://nuget.codeplex.com/discussions/578408) it seems that nobody there was able (willing? interested?) to try to provide any insight.

As we're unable to identify a cause for the behavior you're seeing and the NuGet team seems inable to assist, I'm leaning towards closing this issue at this time.

Can you advise --?

**Comment by Luceres** [comment]
Today I refreshed to Common.Logging.Portable 3.1.0 without any problems! I have no idea why I had a problem before. I had alot of Xamarin Updates in between, so I think it was a problem on their side. Sorry for any unnecessary work. Thank you for your assistance!!

**Comment by sbohlen** [comment]
Great -- happy to hear that you managed to resolve it on your end; appreciate your circling back to let us know!

**Comment by SchalkVersteeg** [comment]
Hi Steve,

I am struggling to add Common.Logging.Core and Common.Logging.Portable to my Xamarin.Android project, Common.Logging.Core 3.3.1

Here is a screen shot of the Xamarin.Forms pcl nuget directory structure, which is working.
*(Note the MonoAndroid10, MonoTouch10 and Xamarin.iOS10 additions)*
![image](https://cloud.githubusercontent.com/assets/7126541/12295664/3f3ba59c-ba0b-11e5-9414-7da0a862d1a2.png)

*Also the following Directory:*
portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10
