### ISSUE TITLE
Enterprise Library 6.0: The LogWriter has not been set for the Logger static class

### ISSUE THREAD

**Issue by amazzarri** [net-commons/common-logging#84]
When trying to use the Enterprise Library 6.0, the exception " The LogWriter has not been set for the Logger static class" is raised when trying to get a logger (i.e. ILog _log = LogManager.GetLogger("myEnterpriseLibraryLoggerCategory");

I fixed the source code in my own version of the package like so: 

in \common-logging\src\Common.Logging.EntLib60\Logging\EntLib\EntLibLoggerFactoryAdapter.cs, at line 92, the original implementation for property LogWriter was updated from this:

        public LogWriter LogWriter
        {
            get
            {
                if (_logWriter == null)
                {
                    lock (this)
                    {
                        if (_logWriter == null)
                        {
                            _logWriter = Logger.Writer;
                        }
                    }
                }
                return _logWriter;
            }
        }

to this one:

        public LogWriter LogWriter
        {
            get
            {
                if (_logWriter == null)
                {
                    lock (this)
                    {
                        if (_logWriter == null)
                        {
                            DatabaseFactory.SetDatabaseProviderFactory(new DatabaseProviderFactory());
                            Logger.SetLogWriter(new LogWriterFactory().Create());
                            _logWriter = Logger.Writer;
                        }
                    }
                }
                return _logWriter;
            }
        }

Please have a look and check if my fix makes sense (the Database... statement is used for the database logging tracer). I think the implementation was brought straight from enterprise library V5 but for V6 there is a small gotcha when creating the logwriter instance (see for instance http://growingtech.blogspot.it/2013/05/enterprise-library-60-logwriter-has-not.html).

**Comment by Wind010** [comment]
I did the same thing, but just used added the line to \common-logging\src\Common.Logging.EntLib60\Logging\EntLib\EntLibLoggerFactoryAdapter.cs:
Logger.SetLogWriter(new LogWriterFactory().Create());

The workaround is to just call this in your own code which is probably why no change has been made yet:
Logger.SetLogWriter(new LogWriterFactory().Create());

You should fork from the project and contribute to the project.  Submit a pull request and and the project owners can decide to take them or not.

**Comment by sbohlen** [comment]
Fixed in https://github.com/net-commons/common-logging/commit/b9f6fea8af5b0c270258743db1f2ecc0d10428d8.
