### ISSUE TITLE
Common.Logging for .Net 4.5

### ISSUE THREAD

**Issue by drusellers** [net-commons/common-logging#88]
Is there a reason that the NuGet package doesn't have a net45 ?

**Comment by sbohlen** [comment]
Our assumption is that there isn't an actual need for this at this time.

There isn't a specific compilation of Common.Logging for net45 (the net40 binary would be identical to a binary for net45).  When adding the package, if there isn't a perfect match for your project's framework target in the package, NuGet is _supposed_ to fall back to the latest/closest _preceding_ framework moniker as I always understood it.

This means that if you add the package to your .NET 4.5 project, you should get the net40 binary referenced (which would be identical to a binary labeled as net45).  Is this different from what you are experiencing?

Possible I'm (once again!) going to find myself surprised by the actual behavior of NuGet in the wild vs. what had been explained to me in the past :-/  If this is the case, we can certainly add a net45 target, but it will be the _same_ binary as the present net40 (unless we become aware of a need to provide a different net45 compilation target).

Can you advise whether you're experiencing something different --?

**Comment by drusellers** [comment]
Cool. Let me check / try again. And I will report back. :)

**Comment by drusellers** [comment]
Ok, not sure what I had wrong but it works now. Thanks!

**Comment by sbohlen** [comment]
Excellent -- my kinda problem :)
