### ISSUE TITLE
Summary of NLogLoggerFactoryAdapter is wrong value

### ISSUE THREAD

**Issue by Arithmomaniac** [net-commons/common-logging#92]
using Common.Logging.NLog32 package, the following can be seen in the object browser:

    public class NLogLoggerFactoryAdapter :  
            Common.Logging.Factory.AbstractCachingLoggerFactoryAdapter
        Member of Common.Logging.NLog

    Summary:
    Concrete subclass of ILoggerFactoryAdapter specific to NLog 1.0.0.505.
Of course, it should be specific to 3.2.

**Comment by sbohlen** [comment]
Oops -- quite right.  I'll fix that shortly -- unless of course you want to submit a one-line pull-request :)

**Comment by sbohlen** [comment]
Fixed in Commit https://github.com/net-commons/common-logging/commit/9c3e5af3abd35b0e51e569af94bf971366f792a3.
