### ISSUE TITLE
Please add support for NLog 4.0

### ISSUE THREAD

**Issue by PeterDefendo** [net-commons/common-logging#96]
NLog 4.0 was released a few days ago and it has some breaking changes more information can be found here http://nlog-project.org/2015/06/09/nlog-4-has-been-released.html

**Comment by sbohlen** [comment]
Thanks for letting us know; we'll add support for this shortly and update NuGet packages accordingly.

**Comment by DashNY** [comment]
+1 and thank you for doing a great job with the Common.Logging component. Really easy to work with.

**Comment by OrangeShark** [comment]
:+1:

**Comment by sbohlen** [comment]
Completed yesterday with Commit https://github.com/net-commons/common-logging/commit/922658a55c7c10c7f0b8e689eea1b460792c9a6e and version Common.Logging 3.2 released and pushed to NuGet.
