### ISSUE TITLE
Common.Logging.Log4Net1213 has incorrect log4net package dependency

### ISSUE THREAD

**Issue by coderjoe** [net-commons/common-logging#98]
The nuspec for Common.Logging.Log4Net1213 requests a dependency of log4net 1.2.13, but the log4net nuget package doesn't seem to be following its assembly version scheme.

log4net [1.2.13] is provided in the 2.0.3 log4net nuget package.

Normally this doesn't cause a problem, but our project has numerous 3rd party dependencies some of which rely on a particular version of log4net, and nuget's version resolution is grabbing Log4Net >= 1.2.13 (which 2.0.0 satisfies... but is actually 1.2.11 causing assembly binding problems.

**Comment by coderjoe** [comment]
In short, Common.Logging.Log4Net1213 should be depending on version 2.0.3 of the log4net nuget package (which is the correct assembly version).

**Comment by sbohlen** [comment]
Understood; we'll correct this shortly and post an updated package to NuGet.  Thanks for identifying this issue.

**Comment by sbohlen** [comment]
I'm traveling and won't be able to look into this until early next week.

**Comment by sbohlen** [comment]
Fixed in https://github.com/net-commons/common-logging/commit/f9964f86f5ae409af62f26d599db555e04884f59.

**Comment by coderjoe** [comment]
Fantastic, this will make my life much easier come Monday. Thanks! :+1:
