### ISSUE TITLE
Question: Common.Logging.Portable application in a PCL code

### ISSUE THREAD

**Issue by uwaka** [net-commons/common-logging#99]
Hi
I'm trying to implement logging in PCL and I've come upon the Common.Logging.Portable.
Started experimenting a little and got stuck. My conundrum is as follows-
It is my understanding that Common.Logging is an interface which would then connect to NLog/ Log4Net- so for the concrete implementation I'd grab one of those guys' nuget into my project and configure as required. But neither Log4Net/NLog have an implementation for PCL so I can't add any of those nuget packages to my PCL project. What am I missing?

**Comment by sbohlen** [comment]
No, you're not missing anything, that's quite correct (none of the logging
frameworks themselves offer PCL implementations.

The way to think about Common.Logging's PCL support is that the logging
*abstractions* in Common.Logging (e.g., ILog) are what you want to
reference in your own PCL assemblies.  Then in your own PCL assemblies you
code to those PCL-based abstractions exposed by Common.Logging.

In non-PCL assemblies (yours or those of others) that reference your own
PCL assemblies (and by implication, the same PCL abstractions assembly from
Common.Logging), you would reference the concrete LogAdapter classes from
Common.Logging and the specific logger you want.


Imagine something sort of like this....

YourPCLProject
  --ref--> Common.Logging.Portable.dll

SomeNonPCLProject
  --ref--> YourPCLProject
  --ref--> Common.Logging.Portable.dll
  --ref--> Common.Logging.Log4Net1211.dll
  --ref--> Log4Net.dll

Does that make sense --?


Steve Bohlen
sbohlen@gmail.com
http://blog.unhandled-exceptions.com
http://twitter.com/sbohlen
